import { Disc3, Droplets, Zap, Thermometer, Wrench, Shield } from "lucide-react"

export const categories = [
  {
    id: "tires",
    name: "Tires & Wheels",
    icon: Disc3,
    description: "Everything from pressure checks to changing a flat",
    skillCount: 8,
    color: "text-primary",
    bgColor: "bg-primary/10",
  },
  {
    id: "fluids",
    name: "Fluids & Filters",
    icon: Droplets,
    description: "Oil, coolant, brake fluid, and more",
    skillCount: 10,
    color: "text-accent",
    bgColor: "bg-accent/10",
  },
  {
    id: "electrical",
    name: "Electrical",
    icon: Zap,
    description: "Battery, jump starts, and basic wiring",
    skillCount: 6,
    color: "text-primary",
    bgColor: "bg-primary/10",
  },
  {
    id: "climate",
    name: "Climate Control",
    icon: Thermometer,
    description: "A/C, heating, and cabin comfort",
    skillCount: 4,
    color: "text-accent",
    bgColor: "bg-accent/10",
  },
  {
    id: "mechanical",
    name: "Mechanical Basics",
    icon: Wrench,
    description: "Brakes, suspension, and engine fundamentals",
    skillCount: 12,
    color: "text-primary",
    bgColor: "bg-primary/10",
  },
  {
    id: "safety",
    name: "Safety & Emergency",
    icon: Shield,
    description: "What to do when things go wrong",
    skillCount: 7,
    color: "text-accent",
    bgColor: "bg-accent/10",
  },
]

export type Difficulty = "beginner" | "intermediate" | "advanced"

export interface Skill {
  id: string
  categoryId: string
  title: string
  description: string
  difficulty: Difficulty
  xp: number
  duration: string
  completed: boolean
  locked: boolean
}

export const skills: Skill[] = [
  // Tires & Wheels
  {
    id: "tire-pressure",
    categoryId: "tires",
    title: "Check Tire Pressure",
    description: "Learn to use a pressure gauge and find your car's recommended PSI",
    difficulty: "beginner",
    xp: 50,
    duration: "5 min",
    completed: true,
    locked: false,
  },
  {
    id: "tire-tread",
    categoryId: "tires",
    title: "Inspect Tire Tread",
    description: "The penny test and signs of uneven wear",
    difficulty: "beginner",
    xp: 50,
    duration: "5 min",
    completed: true,
    locked: false,
  },
  {
    id: "change-tire",
    categoryId: "tires",
    title: "Change a Flat Tire",
    description: "Step-by-step guide to swapping a tire roadside",
    difficulty: "intermediate",
    xp: 150,
    duration: "15 min",
    completed: false,
    locked: false,
  },
  {
    id: "rotate-tires",
    categoryId: "tires",
    title: "Rotate Your Tires",
    description: "DIY tire rotation patterns and when to do it",
    difficulty: "intermediate",
    xp: 100,
    duration: "10 min",
    completed: false,
    locked: false,
  },
  {
    id: "wheel-alignment",
    categoryId: "tires",
    title: "Understand Wheel Alignment",
    description: "Signs you need an alignment and what it costs",
    difficulty: "beginner",
    xp: 75,
    duration: "8 min",
    completed: false,
    locked: true,
  },
  {
    id: "spare-tire",
    categoryId: "tires",
    title: "Locate & Inspect Your Spare",
    description: "Find your spare and make sure it's ready",
    difficulty: "beginner",
    xp: 50,
    duration: "5 min",
    completed: false,
    locked: false,
  },
  {
    id: "tire-sizes",
    categoryId: "tires",
    title: "Decode Tire Sizes",
    description: "What those numbers on your tire sidewall mean",
    difficulty: "beginner",
    xp: 75,
    duration: "7 min",
    completed: false,
    locked: false,
  },
  {
    id: "buy-tires",
    categoryId: "tires",
    title: "Buy the Right Tires",
    description: "How to choose tires and avoid overpaying",
    difficulty: "intermediate",
    xp: 125,
    duration: "12 min",
    completed: false,
    locked: true,
  },
  
  // Fluids & Filters
  {
    id: "check-oil",
    categoryId: "fluids",
    title: "Check Your Oil Level",
    description: "How to read the dipstick and what the oil looks like",
    difficulty: "beginner",
    xp: 50,
    duration: "5 min",
    completed: true,
    locked: false,
  },
  {
    id: "oil-change-basics",
    categoryId: "fluids",
    title: "Oil Change Basics",
    description: "When to change oil and what type you need",
    difficulty: "beginner",
    xp: 75,
    duration: "8 min",
    completed: false,
    locked: false,
  },
  {
    id: "diy-oil-change",
    categoryId: "fluids",
    title: "DIY Oil Change",
    description: "Full walkthrough of changing your own oil",
    difficulty: "intermediate",
    xp: 200,
    duration: "20 min",
    completed: false,
    locked: false,
  },
  {
    id: "coolant-check",
    categoryId: "fluids",
    title: "Check & Top Off Coolant",
    description: "Prevent overheating with proper coolant levels",
    difficulty: "beginner",
    xp: 50,
    duration: "5 min",
    completed: false,
    locked: false,
  },
  {
    id: "brake-fluid",
    categoryId: "fluids",
    title: "Inspect Brake Fluid",
    description: "Why brake fluid matters and when to replace it",
    difficulty: "intermediate",
    xp: 100,
    duration: "8 min",
    completed: false,
    locked: false,
  },
  {
    id: "windshield-fluid",
    categoryId: "fluids",
    title: "Refill Washer Fluid",
    description: "The easiest car maintenance task",
    difficulty: "beginner",
    xp: 25,
    duration: "3 min",
    completed: true,
    locked: false,
  },
  {
    id: "air-filter",
    categoryId: "fluids",
    title: "Replace Air Filter",
    description: "A 5-minute job that improves performance",
    difficulty: "beginner",
    xp: 75,
    duration: "7 min",
    completed: false,
    locked: false,
  },
  {
    id: "cabin-filter",
    categoryId: "fluids",
    title: "Replace Cabin Air Filter",
    description: "Breathe cleaner air inside your car",
    difficulty: "beginner",
    xp: 75,
    duration: "7 min",
    completed: false,
    locked: false,
  },
  {
    id: "transmission-fluid",
    categoryId: "fluids",
    title: "Check Transmission Fluid",
    description: "For automatic and manual transmissions",
    difficulty: "intermediate",
    xp: 100,
    duration: "10 min",
    completed: false,
    locked: true,
  },
  {
    id: "power-steering",
    categoryId: "fluids",
    title: "Power Steering Fluid",
    description: "Keep your steering smooth and responsive",
    difficulty: "beginner",
    xp: 50,
    duration: "5 min",
    completed: false,
    locked: false,
  },
  
  // Electrical
  {
    id: "jump-start",
    categoryId: "electrical",
    title: "Jump Start a Car",
    description: "The right way to use jumper cables",
    difficulty: "beginner",
    xp: 100,
    duration: "10 min",
    completed: false,
    locked: false,
  },
  {
    id: "battery-basics",
    categoryId: "electrical",
    title: "Battery Basics",
    description: "How to test, maintain, and replace your battery",
    difficulty: "beginner",
    xp: 75,
    duration: "8 min",
    completed: false,
    locked: false,
  },
  {
    id: "replace-fuse",
    categoryId: "electrical",
    title: "Find & Replace a Fuse",
    description: "When your lights or radio suddenly stop working",
    difficulty: "beginner",
    xp: 75,
    duration: "7 min",
    completed: false,
    locked: false,
  },
  {
    id: "headlight-bulb",
    categoryId: "electrical",
    title: "Replace Headlight Bulb",
    description: "A simple fix that saves you a shop visit",
    difficulty: "intermediate",
    xp: 100,
    duration: "10 min",
    completed: false,
    locked: false,
  },
  {
    id: "read-dash-lights",
    categoryId: "electrical",
    title: "Understand Dashboard Lights",
    description: "What each warning light means",
    difficulty: "beginner",
    xp: 100,
    duration: "12 min",
    completed: false,
    locked: false,
  },
  {
    id: "alternator-check",
    categoryId: "electrical",
    title: "Test Your Alternator",
    description: "Is it the battery or the alternator?",
    difficulty: "intermediate",
    xp: 125,
    duration: "10 min",
    completed: false,
    locked: true,
  },
  
  // Climate Control
  {
    id: "ac-basics",
    categoryId: "climate",
    title: "A/C System Basics",
    description: "How your car's air conditioning works",
    difficulty: "beginner",
    xp: 75,
    duration: "8 min",
    completed: false,
    locked: false,
  },
  {
    id: "ac-not-cold",
    categoryId: "climate",
    title: "A/C Not Blowing Cold?",
    description: "Diagnose common A/C issues",
    difficulty: "intermediate",
    xp: 100,
    duration: "10 min",
    completed: false,
    locked: false,
  },
  {
    id: "heater-issues",
    categoryId: "climate",
    title: "Heater Not Working?",
    description: "Why your heater might be failing",
    difficulty: "intermediate",
    xp: 100,
    duration: "10 min",
    completed: false,
    locked: false,
  },
  {
    id: "defrost-tips",
    categoryId: "climate",
    title: "Defrost Like a Pro",
    description: "Clear fog and ice quickly",
    difficulty: "beginner",
    xp: 50,
    duration: "5 min",
    completed: false,
    locked: false,
  },
  
  // Mechanical Basics
  {
    id: "brake-inspection",
    categoryId: "mechanical",
    title: "Inspect Your Brakes",
    description: "Signs your brakes need attention",
    difficulty: "beginner",
    xp: 100,
    duration: "10 min",
    completed: false,
    locked: false,
  },
  {
    id: "brake-noises",
    categoryId: "mechanical",
    title: "Brake Noises Decoded",
    description: "What squeaking, grinding, and clicking mean",
    difficulty: "beginner",
    xp: 75,
    duration: "8 min",
    completed: false,
    locked: false,
  },
  {
    id: "brake-pads",
    categoryId: "mechanical",
    title: "When to Replace Brake Pads",
    description: "Don't wait until it's dangerous",
    difficulty: "intermediate",
    xp: 100,
    duration: "10 min",
    completed: false,
    locked: false,
  },
  {
    id: "engine-sounds",
    categoryId: "mechanical",
    title: "Identify Engine Sounds",
    description: "What's normal vs. what needs attention",
    difficulty: "intermediate",
    xp: 125,
    duration: "12 min",
    completed: false,
    locked: false,
  },
  {
    id: "check-engine-light",
    categoryId: "mechanical",
    title: "Check Engine Light",
    description: "What it means and what to do",
    difficulty: "beginner",
    xp: 100,
    duration: "10 min",
    completed: false,
    locked: false,
  },
  {
    id: "wiper-blades",
    categoryId: "mechanical",
    title: "Replace Wiper Blades",
    description: "Cheap and easy maintenance",
    difficulty: "beginner",
    xp: 50,
    duration: "5 min",
    completed: false,
    locked: false,
  },
  
  // Safety & Emergency
  {
    id: "emergency-kit",
    categoryId: "safety",
    title: "Build an Emergency Kit",
    description: "What every car should have",
    difficulty: "beginner",
    xp: 75,
    duration: "8 min",
    completed: false,
    locked: false,
  },
  {
    id: "roadside-safety",
    categoryId: "safety",
    title: "Roadside Safety",
    description: "What to do when you break down",
    difficulty: "beginner",
    xp: 100,
    duration: "10 min",
    completed: false,
    locked: false,
  },
  {
    id: "accident-steps",
    categoryId: "safety",
    title: "After an Accident",
    description: "Step-by-step guide for what to do",
    difficulty: "beginner",
    xp: 125,
    duration: "12 min",
    completed: false,
    locked: false,
  },
  {
    id: "overheating",
    categoryId: "safety",
    title: "Car Overheating?",
    description: "How to handle it safely",
    difficulty: "intermediate",
    xp: 100,
    duration: "10 min",
    completed: false,
    locked: false,
  },
  {
    id: "locked-out",
    categoryId: "safety",
    title: "Locked Out of Your Car",
    description: "Options when you're stuck",
    difficulty: "beginner",
    xp: 50,
    duration: "5 min",
    completed: false,
    locked: false,
  },
  {
    id: "tow-truck",
    categoryId: "safety",
    title: "Calling a Tow Truck",
    description: "How to not get ripped off",
    difficulty: "beginner",
    xp: 75,
    duration: "7 min",
    completed: false,
    locked: false,
  },
  {
    id: "insurance-claim",
    categoryId: "safety",
    title: "File an Insurance Claim",
    description: "Navigate the process smoothly",
    difficulty: "intermediate",
    xp: 100,
    duration: "10 min",
    completed: false,
    locked: true,
  },
]
